//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaContextInterfaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaContextInterface), typeof(System.Object));
		L.RegFunction("UpdateField", UpdateField);
		L.RegFunction("UpdateCollection", UpdateCollection);
		L.RegFunction("UpdateViewModel", UpdateViewModel);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaContextInterface obj = (LuaContextInterface)ToLua.CheckObject(L, 1, typeof(LuaContextInterface));
			string arg0 = ToLua.CheckString(L, 2);
			obj.UpdateField(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateCollection(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaContextInterface obj = (LuaContextInterface)ToLua.CheckObject(L, 1, typeof(LuaContextInterface));
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.UpdateCollection(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateViewModel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaContextInterface obj = (LuaContextInterface)ToLua.CheckObject(L, 1, typeof(LuaContextInterface));
			obj.UpdateViewModel();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

